---
provider:
  name: ec2
  virtualization: hvm
  enhanced_networking: simple
  # credentials:
  #   access-key: AFAKEACCESSKEYFORAWS
  #   secret-key: thes3cr3tkeyf0ryourawsaccount/FS4d8Qdva
bootstrapper:
  workspace: /target
image:
  name: kali-{system.release}-{system.architecture}-{provider.virtualization}-{%Y}-{%m}-{%d}-ebs
  description: Kali {system.release} {system.architecture}
system:
  release: sana
  architecture: amd64
  bootloader: extlinux
  charmap: UTF-8
  locale: en_US
  timezone: UTC
volume:
  backing: ebs
  partitions:
    type: none
    root:
      filesystem: ext4
      size: 8GiB
packages:
  mirror: http://http.kali.org/kali
plugins:
  cloud_init:
    metadata_sources: Ec2
    username: admin
